
package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "OtsiLiveDataSyncToCmsSoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface OtsiLiveDataSyncToCmsSoap {


    /**
     * 
     * @param ownershipType
     * @param horsePower
     * @param financerPin
     * @param makerClass
     * @param insuranceValidFrom
     * @param fcIssuedBy
     * @param ownerMobileNo
     * @param ownerPanNo
     * @param ownerState
     * @param vehicleRegisteredDate
     * @param tandomAxelWeight
     * @param fcNumber
     * @param vehicleNumber
     * @param financerPhoneNO
     * @param vehicleType
     * @param height
     * @param engineNo
     * @param financerName
     * @param driverSeatingCapacity
     * @param permitNo
     * @param dealerAddress3
     * @param vehicleCC
     * @param vehicleIssuePlace
     * @param manufactureMonthYear
     * @param fcChallanNo
     * @param dealerAddress1
     * @param vehicleStatus
     * @param dealerAddress2
     * @param oneDistrictPermit
     * @param wheelBase
     * @param standingCapacity
     * @param permitRouteType
     * @param taxPaymentPeriod
     * @param financerState
     * @param nocOfficeCode
     * @param financerEmailId
     * @param permitLadenWeight
     * @param otherAxelTyreSizes
     * @param ownerFirstName
     * @param goodsDescription
     * @param hypothecationType
     * @param vehicleOldNo
     * @param insuranceValidTo
     * @param rearAxelTyreSizes
     * @param permitValidToDate
     * @param authorizationNo
     * @param ownerAge
     * @param insuranceCompanyName
     * @param growssWeightRegistrationTime
     * @param taxDemandDate
     * @param taxQuarterStartDate
     * @param insuranceNo
     * @param chassisNo
     * @param width
     * @param routeDescription
     * @param cylenders
     * @param taxPenaltyAmount
     * @param seatingCapacity
     * @param bodyType
     * @param fronWeight
     * @param taxDemandAmount
     * @param previousRegisteredOfficeState
     * @param fuel
     * @param dealerAddressPinCode
     * @param taxExemption
     * @param dealerState
     * @param makerName
     * @param permitValidFromDate
     * @param ownerMiddileName
     * @param dealerName
     * @param fcValidToDate
     * @param applicationno
     * @param unleadenWeight
     * @param growssWeightCertificate
     * @param fcValidFromDate
     * @param hangingCapacity
     * @param ownerVoterId
     * @param authToDate
     * @param tandomAxelTyreSizes
     * @param taxPaidOfficeCode
     * @param permitIssueDate
     * @param financeAggrementDate
     * @param governmentVehicle
     * @param permitClass
     * @param ownerCity
     * @param vehicleRegistrationValidUpto
     * @param ownerAddress2
     * @param taxPaidStateCode
     * @param ownerAddress1
     * @param twoDistrictPermit
     * @param ownerAddress3
     * @param ownerPin
     * @param reservedSpecialNo
     * @param color
     * @param previousRegisteredOfficeName
     * @param vehicleIsRTC
     * @param dealerCity
     * @param fronAxelTyreSizes
     * @param financerAddress2
     * @param axelType
     * @param financerAddress3
     * @param financerFaxNo
     * @param financerAddress1
     * @param authFromDate
     * @param permitType
     * @param ownerFatherName
     * @param otherAxelWeight
     * @param fcIssuedDate
     * @param vehicleIsNewOld
     * @param vehicleClass
     * @param taxValidUpto
     * @param ownerLastName
     * @param length
     * @param transactionDate
     * @param taxCollectedAmount
     * @param fcApprovedBy
     * @param remarks
     * @param rearWeight
     * @param financerCity
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "OtsiLiveDataSyncToCMS", action = "http://tempuri.org/OtsiLiveDataSyncToCMS")
    @WebResult(name = "OtsiLiveDataSyncToCMSResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "OtsiLiveDataSyncToCMS", targetNamespace = "http://tempuri.org/", className = "org.tempuri.OtsiLiveDataSyncToCMS")
    @ResponseWrapper(localName = "OtsiLiveDataSyncToCMSResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.OtsiLiveDataSyncToCMSResponse")
    public String otsiLiveDataSyncToCMS(
        @WebParam(name = "vehicleNumber", targetNamespace = "http://tempuri.org/")
        String vehicleNumber,
        @WebParam(name = "vehicleRegisteredDate", targetNamespace = "http://tempuri.org/")
        String vehicleRegisteredDate,
        @WebParam(name = "vehicleRegistrationValidUpto", targetNamespace = "http://tempuri.org/")
        String vehicleRegistrationValidUpto,
        @WebParam(name = "vehicleIssuePlace", targetNamespace = "http://tempuri.org/")
        String vehicleIssuePlace,
        @WebParam(name = "vehicleStatus", targetNamespace = "http://tempuri.org/")
        String vehicleStatus,
        @WebParam(name = "remarks", targetNamespace = "http://tempuri.org/")
        String remarks,
        @WebParam(name = "ownershipType", targetNamespace = "http://tempuri.org/")
        String ownershipType,
        @WebParam(name = "ownerFirstName", targetNamespace = "http://tempuri.org/")
        String ownerFirstName,
        @WebParam(name = "ownerMiddileName", targetNamespace = "http://tempuri.org/")
        String ownerMiddileName,
        @WebParam(name = "ownerLastName", targetNamespace = "http://tempuri.org/")
        String ownerLastName,
        @WebParam(name = "ownerAge", targetNamespace = "http://tempuri.org/")
        String ownerAge,
        @WebParam(name = "ownerFatherName", targetNamespace = "http://tempuri.org/")
        String ownerFatherName,
        @WebParam(name = "ownerPanNo", targetNamespace = "http://tempuri.org/")
        String ownerPanNo,
        @WebParam(name = "ownerVoterId", targetNamespace = "http://tempuri.org/")
        String ownerVoterId,
        @WebParam(name = "ownerMobileNo", targetNamespace = "http://tempuri.org/")
        String ownerMobileNo,
        @WebParam(name = "ownerAddress1", targetNamespace = "http://tempuri.org/")
        String ownerAddress1,
        @WebParam(name = "ownerAddress2", targetNamespace = "http://tempuri.org/")
        String ownerAddress2,
        @WebParam(name = "ownerAddress3", targetNamespace = "http://tempuri.org/")
        String ownerAddress3,
        @WebParam(name = "ownerCity", targetNamespace = "http://tempuri.org/")
        String ownerCity,
        @WebParam(name = "ownerState", targetNamespace = "http://tempuri.org/")
        String ownerState,
        @WebParam(name = "ownerPin", targetNamespace = "http://tempuri.org/")
        String ownerPin,
        @WebParam(name = "vehicleOldNo", targetNamespace = "http://tempuri.org/")
        String vehicleOldNo,
        @WebParam(name = "previousRegisteredOfficeName", targetNamespace = "http://tempuri.org/")
        String previousRegisteredOfficeName,
        @WebParam(name = "previousRegisteredOfficeState", targetNamespace = "http://tempuri.org/")
        String previousRegisteredOfficeState,
        @WebParam(name = "governmentVehicle", targetNamespace = "http://tempuri.org/")
        String governmentVehicle,
        @WebParam(name = "reservedSpecialNo", targetNamespace = "http://tempuri.org/")
        String reservedSpecialNo,
        @WebParam(name = "vehicleIsRTC", targetNamespace = "http://tempuri.org/")
        String vehicleIsRTC,
        @WebParam(name = "insuranceNo", targetNamespace = "http://tempuri.org/")
        String insuranceNo,
        @WebParam(name = "insuranceCompanyName", targetNamespace = "http://tempuri.org/")
        String insuranceCompanyName,
        @WebParam(name = "insuranceValidFrom", targetNamespace = "http://tempuri.org/")
        String insuranceValidFrom,
        @WebParam(name = "insuranceValidTo", targetNamespace = "http://tempuri.org/")
        String insuranceValidTo,
        @WebParam(name = "makerName", targetNamespace = "http://tempuri.org/")
        String makerName,
        @WebParam(name = "makerClass", targetNamespace = "http://tempuri.org/")
        String makerClass,
        @WebParam(name = "dealerName", targetNamespace = "http://tempuri.org/")
        String dealerName,
        @WebParam(name = "dealerAddress1", targetNamespace = "http://tempuri.org/")
        String dealerAddress1,
        @WebParam(name = "dealerAddress2", targetNamespace = "http://tempuri.org/")
        String dealerAddress2,
        @WebParam(name = "dealerAddress3", targetNamespace = "http://tempuri.org/")
        String dealerAddress3,
        @WebParam(name = "dealerCity", targetNamespace = "http://tempuri.org/")
        String dealerCity,
        @WebParam(name = "dealerState", targetNamespace = "http://tempuri.org/")
        String dealerState,
        @WebParam(name = "dealerAddressPinCode", targetNamespace = "http://tempuri.org/")
        String dealerAddressPinCode,
        @WebParam(name = "vehicleClass", targetNamespace = "http://tempuri.org/")
        String vehicleClass,
        @WebParam(name = "chassisNo", targetNamespace = "http://tempuri.org/")
        String chassisNo,
        @WebParam(name = "engineNo", targetNamespace = "http://tempuri.org/")
        String engineNo,
        @WebParam(name = "vehicleType", targetNamespace = "http://tempuri.org/")
        String vehicleType,
        @WebParam(name = "bodyType", targetNamespace = "http://tempuri.org/")
        String bodyType,
        @WebParam(name = "wheelBase", targetNamespace = "http://tempuri.org/")
        String wheelBase,
        @WebParam(name = "fuel", targetNamespace = "http://tempuri.org/")
        String fuel,
        @WebParam(name = "vehicleCC", targetNamespace = "http://tempuri.org/")
        String vehicleCC,
        @WebParam(name = "cylenders", targetNamespace = "http://tempuri.org/")
        String cylenders,
        @WebParam(name = "seatingCapacity", targetNamespace = "http://tempuri.org/")
        String seatingCapacity,
        @WebParam(name = "driverSeatingCapacity", targetNamespace = "http://tempuri.org/")
        String driverSeatingCapacity,
        @WebParam(name = "standingCapacity", targetNamespace = "http://tempuri.org/")
        String standingCapacity,
        @WebParam(name = "color", targetNamespace = "http://tempuri.org/")
        String color,
        @WebParam(name = "vehicleIsNewOld", targetNamespace = "http://tempuri.org/")
        String vehicleIsNewOld,
        @WebParam(name = "manufactureMonthYear", targetNamespace = "http://tempuri.org/")
        String manufactureMonthYear,
        @WebParam(name = "horsePower", targetNamespace = "http://tempuri.org/")
        String horsePower,
        @WebParam(name = "unleadenWeight", targetNamespace = "http://tempuri.org/")
        String unleadenWeight,
        @WebParam(name = "growssWeightCertificate", targetNamespace = "http://tempuri.org/")
        String growssWeightCertificate,
        @WebParam(name = "growssWeightRegistrationTime", targetNamespace = "http://tempuri.org/")
        String growssWeightRegistrationTime,
        @WebParam(name = "fronAxelTyreSizes", targetNamespace = "http://tempuri.org/")
        String fronAxelTyreSizes,
        @WebParam(name = "rearAxelTyreSizes", targetNamespace = "http://tempuri.org/")
        String rearAxelTyreSizes,
        @WebParam(name = "otherAxelTyreSizes", targetNamespace = "http://tempuri.org/")
        String otherAxelTyreSizes,
        @WebParam(name = "tandomAxelTyreSizes", targetNamespace = "http://tempuri.org/")
        String tandomAxelTyreSizes,
        @WebParam(name = "fronWeight", targetNamespace = "http://tempuri.org/")
        String fronWeight,
        @WebParam(name = "rearWeight", targetNamespace = "http://tempuri.org/")
        String rearWeight,
        @WebParam(name = "otherAxelWeight", targetNamespace = "http://tempuri.org/")
        String otherAxelWeight,
        @WebParam(name = "tandomAxelWeight", targetNamespace = "http://tempuri.org/")
        String tandomAxelWeight,
        @WebParam(name = "axelType", targetNamespace = "http://tempuri.org/")
        String axelType,
        @WebParam(name = "length", targetNamespace = "http://tempuri.org/")
        String length,
        @WebParam(name = "width", targetNamespace = "http://tempuri.org/")
        String width,
        @WebParam(name = "height", targetNamespace = "http://tempuri.org/")
        String height,
        @WebParam(name = "hangingCapacity", targetNamespace = "http://tempuri.org/")
        String hangingCapacity,
        @WebParam(name = "taxExemption", targetNamespace = "http://tempuri.org/")
        String taxExemption,
        @WebParam(name = "taxPaidOfficeCode", targetNamespace = "http://tempuri.org/")
        String taxPaidOfficeCode,
        @WebParam(name = "taxPaidStateCode", targetNamespace = "http://tempuri.org/")
        String taxPaidStateCode,
        @WebParam(name = "taxPaymentPeriod", targetNamespace = "http://tempuri.org/")
        String taxPaymentPeriod,
        @WebParam(name = "taxDemandAmount", targetNamespace = "http://tempuri.org/")
        String taxDemandAmount,
        @WebParam(name = "taxPenaltyAmount", targetNamespace = "http://tempuri.org/")
        String taxPenaltyAmount,
        @WebParam(name = "taxCollectedAmount", targetNamespace = "http://tempuri.org/")
        String taxCollectedAmount,
        @WebParam(name = "taxDemandDate", targetNamespace = "http://tempuri.org/")
        String taxDemandDate,
        @WebParam(name = "taxQuarterStartDate", targetNamespace = "http://tempuri.org/")
        String taxQuarterStartDate,
        @WebParam(name = "taxValidUpto", targetNamespace = "http://tempuri.org/")
        String taxValidUpto,
        @WebParam(name = "hypothecationType", targetNamespace = "http://tempuri.org/")
        String hypothecationType,
        @WebParam(name = "financerName", targetNamespace = "http://tempuri.org/")
        String financerName,
        @WebParam(name = "financeAggrementDate", targetNamespace = "http://tempuri.org/")
        String financeAggrementDate,
        @WebParam(name = "financerAddress1", targetNamespace = "http://tempuri.org/")
        String financerAddress1,
        @WebParam(name = "financerAddress2", targetNamespace = "http://tempuri.org/")
        String financerAddress2,
        @WebParam(name = "financerAddress3", targetNamespace = "http://tempuri.org/")
        String financerAddress3,
        @WebParam(name = "financerCity", targetNamespace = "http://tempuri.org/")
        String financerCity,
        @WebParam(name = "financerState", targetNamespace = "http://tempuri.org/")
        String financerState,
        @WebParam(name = "financerPin", targetNamespace = "http://tempuri.org/")
        String financerPin,
        @WebParam(name = "financerFaxNo", targetNamespace = "http://tempuri.org/")
        String financerFaxNo,
        @WebParam(name = "financerPhoneNO", targetNamespace = "http://tempuri.org/")
        String financerPhoneNO,
        @WebParam(name = "financerEmailId", targetNamespace = "http://tempuri.org/")
        String financerEmailId,
        @WebParam(name = "nocOfficeCode", targetNamespace = "http://tempuri.org/")
        String nocOfficeCode,
        @WebParam(name = "APPLICATIONNO", targetNamespace = "http://tempuri.org/")
        String applicationno,
        @WebParam(name = "FcNumber", targetNamespace = "http://tempuri.org/")
        String fcNumber,
        @WebParam(name = "FcIssuedBy", targetNamespace = "http://tempuri.org/")
        String fcIssuedBy,
        @WebParam(name = "FcIssuedDate", targetNamespace = "http://tempuri.org/")
        String fcIssuedDate,
        @WebParam(name = "FcValidFromDate", targetNamespace = "http://tempuri.org/")
        String fcValidFromDate,
        @WebParam(name = "FcValidToDate", targetNamespace = "http://tempuri.org/")
        String fcValidToDate,
        @WebParam(name = "FcApprovedBy", targetNamespace = "http://tempuri.org/")
        String fcApprovedBy,
        @WebParam(name = "FcChallanNo", targetNamespace = "http://tempuri.org/")
        String fcChallanNo,
        @WebParam(name = "PermitNo", targetNamespace = "http://tempuri.org/")
        String permitNo,
        @WebParam(name = "PermitClass", targetNamespace = "http://tempuri.org/")
        String permitClass,
        @WebParam(name = "PermitType", targetNamespace = "http://tempuri.org/")
        String permitType,
        @WebParam(name = "PermitIssueDate", targetNamespace = "http://tempuri.org/")
        String permitIssueDate,
        @WebParam(name = "PermitValidFromDate", targetNamespace = "http://tempuri.org/")
        String permitValidFromDate,
        @WebParam(name = "PermitValidToDate", targetNamespace = "http://tempuri.org/")
        String permitValidToDate,
        @WebParam(name = "AuthorizationNo", targetNamespace = "http://tempuri.org/")
        String authorizationNo,
        @WebParam(name = "AuthFromDate", targetNamespace = "http://tempuri.org/")
        String authFromDate,
        @WebParam(name = "AuthToDate", targetNamespace = "http://tempuri.org/")
        String authToDate,
        @WebParam(name = "RouteDescription", targetNamespace = "http://tempuri.org/")
        String routeDescription,
        @WebParam(name = "GoodsDescription", targetNamespace = "http://tempuri.org/")
        String goodsDescription,
        @WebParam(name = "PermitLadenWeight", targetNamespace = "http://tempuri.org/")
        String permitLadenWeight,
        @WebParam(name = "PermitRouteType", targetNamespace = "http://tempuri.org/")
        String permitRouteType,
        @WebParam(name = "OneDistrictPermit", targetNamespace = "http://tempuri.org/")
        String oneDistrictPermit,
        @WebParam(name = "TwoDistrictPermit", targetNamespace = "http://tempuri.org/")
        String twoDistrictPermit,
        @WebParam(name = "TransactionDate", targetNamespace = "http://tempuri.org/")
        String transactionDate);

}
