
package org.tempuri;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */

@WebServiceClient(name = "OtsiLiveDataSyncToCms1", targetNamespace = "http://tempuri.org/", wsdlLocation = "classpath:WS.xml" )
public class OtsiLiveDataSyncToCms1
    extends Service
{

    private final static URL OTSILIVEDATASYNCTOCMS1_WSDL_LOCATION;
    private final static WebServiceException OTSILIVEDATASYNCTOCMS1_EXCEPTION;
    private final static QName OTSILIVEDATASYNCTOCMS1_QNAME = new QName("http://tempuri.org/", "OtsiLiveDataSyncToCms1");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
        	url = new URL("classpath:WS.xml");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        OTSILIVEDATASYNCTOCMS1_WSDL_LOCATION = url;
        OTSILIVEDATASYNCTOCMS1_EXCEPTION = e;
    }

    public OtsiLiveDataSyncToCms1() {
        super(__getWsdlLocation(), OTSILIVEDATASYNCTOCMS1_QNAME);
    }

    public OtsiLiveDataSyncToCms1(WebServiceFeature... features) {
        super(__getWsdlLocation(), OTSILIVEDATASYNCTOCMS1_QNAME, features);
    }

    public OtsiLiveDataSyncToCms1(URL wsdlLocation) {
        super(wsdlLocation, OTSILIVEDATASYNCTOCMS1_QNAME);
    }

    public OtsiLiveDataSyncToCms1(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, OTSILIVEDATASYNCTOCMS1_QNAME, features);
    }

    public OtsiLiveDataSyncToCms1(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OtsiLiveDataSyncToCms1(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns OtsiLiveDataSyncToCmsSoap
     */
    @WebEndpoint(name = "OtsiLiveDataSyncToCmsSoap")
    public OtsiLiveDataSyncToCmsSoap getOtsiLiveDataSyncToCmsSoap() {
        return super.getPort(new QName("http://tempuri.org/", "OtsiLiveDataSyncToCmsSoap"), OtsiLiveDataSyncToCmsSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OtsiLiveDataSyncToCmsSoap
     */
    @WebEndpoint(name = "OtsiLiveDataSyncToCmsSoap")
    public OtsiLiveDataSyncToCmsSoap getOtsiLiveDataSyncToCmsSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "OtsiLiveDataSyncToCmsSoap"), OtsiLiveDataSyncToCmsSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (OTSILIVEDATASYNCTOCMS1_EXCEPTION!= null) {
            throw OTSILIVEDATASYNCTOCMS1_EXCEPTION;
        }
        return OTSILIVEDATASYNCTOCMS1_WSDL_LOCATION;
    }

}
