package org.epragati.service.notification;

public enum MessageTemplate {

	NEW_REG_TR(1), NEW_REG_PR(2), NEW_REG_PR_REJECTED(10), // PR REJECTED BY RTO

	// Special number related Templates.1.passcod generated
	SP_NUM_PASSCODE(3), SP_BID_WIN(4), SP_BID_LOOSE(5), SP_BID_TIE(6), SP_BID_LIMITEXCEED(7),

	// Finanicear token
	FIN_TOKEN_NO(8), SP_BID_INTIMATION(9),

	AADHAAR_AUTO_APPROVED(21), // Aadhaar seed auto approved.
	AADHAAR_APPROVED(22), // Aadhaar seed approved by RTA Officer.
	AADHAAR_INITIATED(23), // Aadhaar seed Partially Matched.
	AADHAAR_OPENED(24), // Aadhaar seed Auto Rejected.
	AADHAAR_REJECTED(25), // Aadhaar seed Rejected by RTA Officer.
	SLOTBOOKED(11), SLOTMODIFICATION(12), REG_APPROVAL(13), REG_REJECTED(14), REG_TAXPENDING(15),
	REG_OTHERSTATEPAYMENTPENDING(62), REG_OTHERSTATEVEHICLEWITHPR(68), REG_OSSECONDVEHICLEPAYMENTPENDING(63),
	REG_OSSECONDVEHICLEPAYMENTDONE(66), REG_FINANCIER_TOKEN_GENERATED(74), REG_REUPLOAD(16), RC_SUSPENSION(17),
	RC_CANCELLATION(18), RC_REVOKATION(19), REG_FC(20), P_SUSPENSION(30), P_CANCELLATION(31), P_REVOKATION(32),
	REG_FCSLOT(33), CITIZEN_MOBILE_APP_OTP(35), TOW_TOKENCANCEL_FIN_APPROVED(36), TOW_TOKENCANCEL_FIN_REJECTED(37),
	TOW_TOKEN_GENERATED(38), TOW_BUYER(150), TOW_TOKEN_CANCELED(151), HPA_TOKEN_GENERATED(48), NOC_ISSUED(57),RCFORFINANCE(59),
	NOC_CANCELLED(58), THEFT_INTIMATION(61), THEFT_REVOCATION(162), RENWAL_RC(53), ALTERATION_VEHICLE(55),
	CHANGE_OF_ADDRESS(54), HPT(49), DUPLICATE_RC(52), NEW_FC(132), PERMIT_NEW(64), RENEWAL_PERMIT(65),
	SURRENDER_PERMIT(73), TRANSFER_PERMIT(72), PERMIT_COA(67), VARIATION_PERMIT(69), RENEWAL_AUTH_CARD(70),
	REPLACEMENT_VEHICLE(71), EXTENION_VALIDITY(94), FIN_REGN_SUCCESS(1001), FIN_REGN_STATUS(1002),
	SMART_CARD_PRINT(1003), OFFICER_REG(1004), OFFICER_PWD_RESET(1005), VCR_REG(22318),
	RCFORFINANCECIT(1008),RCFORFINANCEFINAPP(1009),RCFORFINANCECITAPP(10010),RCFORFINANCEREG(10011),STOPPAGEMVI(10012),STOPPAGEDTC(10013),STOPPAGECITIZEN(10014)
	,STOPPAGEAUTOAPPROVEDFORMVI(10015),STOPPAGEAUTOAPPROVEDFORCITIZEN(10016),
	DELERSHIP_APPROVED(259), DELERSHIP_REJECTED(261),EWEBVCR(252525),CARDDISPATCH_EMS(500),RCFORFINANCEFORM37FIN(252526),RCFORFINANCEFORM37CIT(252527),FINANCIERNOTMATCH(252528),
	VEHICHLENOTREPOSSESED(252529);
	

	private Integer id;

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	private MessageTemplate(Integer id) {
		this.id = id;
	}

}
