
package org.epragati.apts.aadhaar;

import java.net.MalformedURLException;
import java.net.URL;

import javax.annotation.PostConstruct;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import org.springframework.beans.factory.annotation.Value;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */

@WebServiceClient(name = "BSNLeKYCWebservices", targetNamespace = "http://services/ecentric/com/xsd", wsdlLocation = "https://auakua.ap.gov.in/auakua/services/BSNLeKYCWebservices?wsdl")
public class BSNLeKYCWebservices
    extends Service
{

    public  static URL BSNLEKYCWEBSERVICES_WSDL_LOCATION;
    public  static WebServiceException BSNLEKYCWEBSERVICES_EXCEPTION;
    private final static QName BSNLEKYCWEBSERVICES_QNAME = new QName("http://services/ecentric/com/xsd", "BSNLeKYCWebservices");
   
    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://auakua.ap.gov.in/auakua/services/BSNLeKYCWebservices?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BSNLEKYCWEBSERVICES_WSDL_LOCATION = url;
        BSNLEKYCWEBSERVICES_EXCEPTION = e;
    }

    public BSNLeKYCWebservices() {
        super(__getWsdlLocation(), BSNLEKYCWEBSERVICES_QNAME);
    }

    public BSNLeKYCWebservices(WebServiceFeature... features) {
        super(__getWsdlLocation(), BSNLEKYCWEBSERVICES_QNAME, features);
    }

    public BSNLeKYCWebservices(URL wsdlLocation) {
        super(wsdlLocation, BSNLEKYCWEBSERVICES_QNAME);
    }

    public BSNLeKYCWebservices(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BSNLEKYCWEBSERVICES_QNAME, features);
    }

    public BSNLeKYCWebservices(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BSNLeKYCWebservices(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BSNLeKYCWebservicesPortType
     */
    @WebEndpoint(name = "BSNLeKYCWebservicesHttpsSoap11Endpoint")
    public BSNLeKYCWebservicesPortType getBSNLeKYCWebservicesHttpsSoap11Endpoint() {
        return super.getPort(new QName("http://services/ecentric/com/xsd", "BSNLeKYCWebservicesHttpsSoap11Endpoint"), BSNLeKYCWebservicesPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BSNLeKYCWebservicesPortType
     */
    @WebEndpoint(name = "BSNLeKYCWebservicesHttpsSoap11Endpoint")
    public BSNLeKYCWebservicesPortType getBSNLeKYCWebservicesHttpsSoap11Endpoint(WebServiceFeature... features) {
        return super.getPort(new QName("http://services/ecentric/com/xsd", "BSNLeKYCWebservicesHttpsSoap11Endpoint"), BSNLeKYCWebservicesPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BSNLEKYCWEBSERVICES_EXCEPTION!= null) {
            throw BSNLEKYCWEBSERVICES_EXCEPTION;
        }
        return BSNLEKYCWEBSERVICES_WSDL_LOCATION;
    }

}
