
package org.epragati.apts.aadhaar;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BSNLeKYCWebservicesPortType", targetNamespace = "http://services/ecentric/com/xsd")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BSNLeKYCWebservicesPortType {


    /**
     * 
     * @param certificateIdentifier
     * @param dataType
     * @param dpId
     * @param rdsId
     * @param uidNum
     * @param agencyCode
     * @param agencyName
     * @param encryptedPid
     * @param encSessionKey
     * @param udc
     * @param mc
     * @param eKYCOption
     * @param mi
     * @param rdsVer
     * @param encHmac
     * @param dc
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:getAadhaarDemographicDataBySRDHSecuredeKYC")
    @WebResult(targetNamespace = "http://services/ecentric/com/xsd")
    @RequestWrapper(localName = "getAadhaarDemographicDataBySRDHSecuredeKYC", targetNamespace = "http://services/ecentric/com/xsd", className = "services.ecentric.com.xsd.GetAadhaarDemographicDataBySRDHSecuredeKYC")
    @ResponseWrapper(localName = "getAadhaarDemographicDataBySRDHSecuredeKYCResponse", targetNamespace = "http://services/ecentric/com/xsd", className = "services.ecentric.com.xsd.GetAadhaarDemographicDataBySRDHSecuredeKYCResponse")
    public String getAadhaarDemographicDataBySRDHSecuredeKYC(
        @WebParam(name = "uid_num", targetNamespace = "http://services/ecentric/com/xsd")
        String uidNum,
        @WebParam(name = "agency_name", targetNamespace = "http://services/ecentric/com/xsd")
        String agencyName,
        @WebParam(name = "agency_code", targetNamespace = "http://services/ecentric/com/xsd")
        String agencyCode,
        @WebParam(name = "encryptedPid", targetNamespace = "http://services/ecentric/com/xsd")
        byte[] encryptedPid,
        @WebParam(name = "encSessionKey", targetNamespace = "http://services/ecentric/com/xsd")
        byte[] encSessionKey,
        @WebParam(name = "encHmac", targetNamespace = "http://services/ecentric/com/xsd")
        byte[] encHmac,
        @WebParam(name = "certificateIdentifier", targetNamespace = "http://services/ecentric/com/xsd")
        String certificateIdentifier,
        @WebParam(name = "eKYCOption", targetNamespace = "http://services/ecentric/com/xsd")
        String eKYCOption,
        @WebParam(name = "dataType", targetNamespace = "http://services/ecentric/com/xsd")
        String dataType,
        @WebParam(name = "udc", targetNamespace = "http://services/ecentric/com/xsd")
        String udc,
        @WebParam(name = "rdsId", targetNamespace = "http://services/ecentric/com/xsd")
        String rdsId,
        @WebParam(name = "rdsVer", targetNamespace = "http://services/ecentric/com/xsd")
        String rdsVer,
        @WebParam(name = "dpId", targetNamespace = "http://services/ecentric/com/xsd")
        String dpId,
        @WebParam(name = "dc", targetNamespace = "http://services/ecentric/com/xsd")
        String dc,
        @WebParam(name = "mi", targetNamespace = "http://services/ecentric/com/xsd")
        String mi,
        @WebParam(name = "mc", targetNamespace = "http://services/ecentric/com/xsd")
        String mc);

    /**
     * 
     * @param encryptedPid
     * @param encSessionKey
     * @param uidNum
     * @param agencyCode
     * @param agencyName
     * @param encHmac
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "OTPProcessingBySRDHSecuredeKYC", action = "urn:OTPProcessingBySRDHSecuredeKYC")
    @WebResult(targetNamespace = "http://services/ecentric/com/xsd")
    @RequestWrapper(localName = "OTPProcessingBySRDHSecuredeKYC", targetNamespace = "http://services/ecentric/com/xsd", className = "services.ecentric.com.xsd.OTPProcessingBySRDHSecuredeKYC")
    @ResponseWrapper(localName = "OTPProcessingBySRDHSecuredeKYCResponse", targetNamespace = "http://services/ecentric/com/xsd", className = "services.ecentric.com.xsd.OTPProcessingBySRDHSecuredeKYCResponse")
    public String otpProcessingBySRDHSecuredeKYC(
        @WebParam(name = "uid_num", targetNamespace = "http://services/ecentric/com/xsd")
        String uidNum,
        @WebParam(name = "agency_name", targetNamespace = "http://services/ecentric/com/xsd")
        String agencyName,
        @WebParam(name = "agency_code", targetNamespace = "http://services/ecentric/com/xsd")
        String agencyCode,
        @WebParam(name = "encryptedPid", targetNamespace = "http://services/ecentric/com/xsd")
        byte[] encryptedPid,
        @WebParam(name = "encSessionKey", targetNamespace = "http://services/ecentric/com/xsd")
        byte[] encSessionKey,
        @WebParam(name = "encHmac", targetNamespace = "http://services/ecentric/com/xsd")
        byte[] encHmac);

    /**
     * 
     * @param uidNum
     * @param agencyCode
     * @param agencyName
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "OTPGenerationBySRDHSecuredeKYC", action = "urn:OTPGenerationBySRDHSecuredeKYC")
    @WebResult(targetNamespace = "http://services/ecentric/com/xsd")
    @RequestWrapper(localName = "OTPGenerationBySRDHSecuredeKYC", targetNamespace = "http://services/ecentric/com/xsd", className = "services.ecentric.com.xsd.OTPGenerationBySRDHSecuredeKYC")
    @ResponseWrapper(localName = "OTPGenerationBySRDHSecuredeKYCResponse", targetNamespace = "http://services/ecentric/com/xsd", className = "services.ecentric.com.xsd.OTPGenerationBySRDHSecuredeKYCResponse")
    public String otpGenerationBySRDHSecuredeKYC(
        @WebParam(name = "uidNum", targetNamespace = "http://services/ecentric/com/xsd")
        String uidNum,
        @WebParam(name = "agencyName", targetNamespace = "http://services/ecentric/com/xsd")
        String agencyName,
        @WebParam(name = "agencyCode", targetNamespace = "http://services/ecentric/com/xsd")
        String agencyCode);

}
